# add_animations.R
css <- readLines("www/styles.css")

new_css <- c(
  "",
  "/* ========================================= */",
  "/* ── WORLD-CLASS PREMIUM ANIMATIONS ─── */",
  "/* ========================================= */",
  "",
  "/* 1. Animated Breathing Background */",
  "body::before {",
  "  background-size: 200% 200%;",
  "  animation: bgPan 20s ease-in-out infinite alternate;",
  "}",
  "@keyframes bgPan {",
  "  0% { background-position: 0% 50%; }",
  "  50% { background-position: 100% 50%; }",
  "  100% { background-position: 0% 50%; }",
  "}",
  "",
  "/* 2. Magnetic 3D Metric Cards */",
  ".metric-card {",
  "  transition: all 0.5s cubic-bezier(0.175, 0.885, 0.32, 1.275) !important;",
  "}",
  ".metric-card:hover {",
  "  transform: translateY(-8px) scale(1.03) !important;",
  "  border-color: var(--cyan) !important;",
  "  box-shadow: 0 15px 35px rgba(207,168,95,.25), inset 0 0 20px rgba(207,168,95,.08) !important;",
  "  z-index: 10;",
  "}",
  "",
  "/* 3. Smooth Floating Cards */",
  ".card {",
  "  transition: all 0.4s cubic-bezier(0.25, 0.8, 0.25, 1) !important;",
  "}",
  ".card:hover {",
  "  transform: translateY(-4px) !important;",
  "  box-shadow: 0 20px 40px rgba(255,26,26,.15), 0 5px 15px rgba(0,0,0,.5) !important;",
  "}",
  "",
  "/* 4. Pulsing Call-To-Action Button */",
  ".btn-primary, .btn-run {",
  "  position: relative;",
  "  overflow: hidden;",
  "  animation: pulseRing 2.5s infinite cubic-bezier(0.4, 0, 0.2, 1);",
  "}",
  "@keyframes pulseRing {",
  "  0% { box-shadow: 0 0 0 0 rgba(255,26,26, 0.6), 0 4px 20px rgba(255,26,26,.25); }",
  "  70% { box-shadow: 0 0 0 12px rgba(255,26,26, 0), 0 4px 20px rgba(255,26,26,.25); }",
  "  100% { box-shadow: 0 0 0 0 rgba(255,26,26, 0), 0 4px 20px rgba(255,26,26,.25); }",
  "}",
  "/* Button Shine Sweep Effect */",
  ".btn-primary::after, .btn-run::after {",
  "  content: ''; position: absolute; top: -50%; left: -100%;",
  "  width: 50%; height: 200%;",
  "  background: linear-gradient(90deg, transparent, rgba(255,255,255,0.25), transparent);",
  "  transform: skewX(-20deg); transition: 0.7s ease;",
  "}",
  ".btn-primary:hover::after, .btn-run:hover::after {",
  "  left: 200%;",
  "}",
  "",
  "/* 5. Insight Blocks Continuous Shimmer */",
  ".insight-block {",
  "  position: relative;",
  "  overflow: hidden;",
  "}",
  ".insight-block::before {",
  "  content: ''; position: absolute; top: 0; left: -100%; width: 50%; height: 100%;",
  "  background: linear-gradient(90deg, transparent, rgba(255,255,255,0.03), transparent);",
  "  animation: shimmer 3s infinite;",
  "}",
  "@keyframes shimmer {",
  "  100% { left: 200%; }",
  "}",
  "",
  "/* 6. Staggered Entrance for Grids */",
  ".grid-2 > div:nth-child(1) { animation-delay: 0.1s; }",
  ".grid-2 > div:nth-child(2) { animation-delay: 0.2s; }",
  ".grid-3 > div:nth-child(1) { animation-delay: 0.1s; }",
  ".grid-3 > div:nth-child(2) { animation-delay: 0.2s; }",
  ".grid-3 > div:nth-child(3) { animation-delay: 0.3s; }",
  ".grid-4 > div:nth-child(1) { animation-delay: 0.1s; }",
  ".grid-4 > div:nth-child(2) { animation-delay: 0.2s; }",
  ".grid-4 > div:nth-child(3) { animation-delay: 0.3s; }",
  ".grid-4 > div:nth-child(4) { animation-delay: 0.4s; }",
  "",
  "/* 7. Slide-In Data Table Rows */",
  "table.dataTable tbody tr {",
  "  animation: fadeLeft 0.5s cubic-bezier(0.2, 0.8, 0.2, 1) both;",
  "}",
  "@keyframes fadeLeft {",
  "  from { opacity: 0; transform: translateX(-15px); }",
  "  to { opacity: 1; transform: translateX(0); }",
  "}",
  "table.dataTable tbody tr:nth-child(1) { animation-delay: 0.05s; }",
  "table.dataTable tbody tr:nth-child(2) { animation-delay: 0.10s; }",
  "table.dataTable tbody tr:nth-child(3) { animation-delay: 0.15s; }",
  "table.dataTable tbody tr:nth-child(4) { animation-delay: 0.20s; }",
  "table.dataTable tbody tr:nth-child(5) { animation-delay: 0.25s; }",
  "table.dataTable tbody tr:nth-child(6) { animation-delay: 0.30s; }",
  "table.dataTable tbody tr:nth-child(7) { animation-delay: 0.35s; }",
  "table.dataTable tbody tr:nth-child(8) { animation-delay: 0.40s; }",
  "table.dataTable tbody tr:nth-child(9) { animation-delay: 0.45s; }",
  "table.dataTable tbody tr:nth-child(10){ animation-delay: 0.50s; }"
)

css <- c(css, new_css)
writeLines(css, "www/styles.css")
cat("Animations added!\n")
